#cloud-config
fqdn: test-VM
keyboard:
  layout: fr
  variant: nodeadkeys
package_update: true
package_upgrade: true
repo_update: true
repo_upgrade: security
packages: 
  - openssh-server
  - python3
  - acl
  - apache2
  - unzip
users:
  - default
  - name: ansible
    gecos: Ansible User
    sudo:  ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCVGosiwgBY2Jh1Xvqxqlkb3gevwI6FBqOsHF5yVSjPrrHfBmAC5h0vZl9KnBM6g68mtiWtuI1Cw3Kh+VAvIuwxms0zps4cLJ/w8DKdG0ZIvol95x1M+FTvH91oqBbGvPq3Zyh3tx+eOI0LNFT50p7xjCylugsf7E7nuMRVje+a45DhqrsEWrCmPxrFonSxlAVjLWY/D1ZJMSC9w+6sDmY7H/JL6RUV0Gfqgki+zVPxaewzph+wYlPvxZ2ObNmytYBMRmHugzqOcF6IndraSRZwb4H2IfNodeg/5QZ/z5KcVAFH0oLtn2DGrzQtcm5m3MixCCEIoTy4nwFAqVvnaMTkKjW1A5CoII/3BxE8c7wAu3sEbFQjbcl5g8GlpbvWJo1hU9tjBnBtZ+gjc4bSx/XwOGf045Vx+tGFSPIgkkRnsODv9DhKPgcbU+oJPlznETMBtBsrWX8t//e9rGhU7mCGoVMijA/W4Xs+N/qnNb2CQ0VQMce6+9IsKeVZdd3+LWbsIY5kkMCH39HA3M455izlKrWFxmoisIeJl5XY0hQIWc30SWwFetlfc3pQJQxRGPYaEvo0Wjm+2Qa2/S884zi+xlq/xqDYDJSbHE90j01v7ld/dhOwt/S7klROmPOUmhJrXXYCf3Ik94R+Gv5OVSsl2X0OQKP7x+ZxLkOpUNQsoQ=="
write_files:
  - path: /etc/issue
    append: true
    content: |
      ens160: \4{ens160}       
power_state:
  delay: now
  mode: reboot
  message: Rebooting machine
  condition: true
runcmd:
  - [ mkdir, /cloud-init-temp/ ]
  - [ wget, -O, /cloud-init-temp/massively.zip, https://html5up.net/massively/download, --no-check-certificate ]
  - [ rm, /var/www/html/index.html ]
  - [ unzip, /cloud-init-temp/massively.zip, -d, /var/www/html/ ]
  - [ chown, -R, www-data:www-data, /var/www/html ]

###########################################################################
############### Encrypt this file to Base64 with command : ################
### base64 ./cloud-init-userdata.yaml > cloud-init-userdata-base64.yaml ###