network:
  version: 2
  ethernets:
    nics:
      match:
        name: ens*
      dhcp4: false
      dhcp6: false
      addresses:
        - 192.168.50.20/24
      routes:
          - to: default
            via: 192.168.50.254
      nameservers:
        search: [urios.local,uriosbeic.local,beic.local]
        addresses: [192.168.200.100,8.8.8.8]

###########################################################################
############### Encrypt this file to Base64 with command : ################
### base64 ./cloud-init-metadata.yaml > cloud-init-metadata-base64.yaml ###